# DEV
spring:
  config:
    activate:
      on-profile: dev
  application:
    name: todolist
  datasource:
    url: "jdbc:postgresql://localhost:54321/todolist"
    username: "postgres"
    password: "todolist-db"
  jpa:
    show-sql: true
    hibernate:
      # Create tables automatically
      ddl-auto: update
---
# TEST
spring:
  config:
    activate:
      on-profile: dev
  application:
    name: todolist
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      # Create tables automatically
      ddl-auto: update